---
title: "Connectivity"
author: "Tomke Stuerner"
date: "06/07/2021"
output: html_document
---

```{r, message=FALSE}
library(hemibrainr)
library(natverse)
library(fafbseg)
library(reticulate)
library(googlesheets4)
library(dplyr)
library(neuprintr)
library(catmaid)
library(catnat)
library(ggplot2)
```

```{r rgl_plotsetup}
rgl_usermat = structure(c(0.98662239,  -0.1360703,  0.08978364, 0, 
                          0.06441419,  -0.1805410, -0.98145604, 0, 
                          0.14975676,   0.9741101, -0.16936085, 0, 
                          0,            0,          0,          1), .Dim = c(4L, 4L))
rgl_zoom = 1
rgl_rect = c(0L, 45L, 1171L, 823L)
```

```{r flywire}
choose_segmentation("flywire31")
catmaid_login() #this only works if you have your credentials saved in your environment
```

get the flywire ids of all MBON, LHCENTs in flywire
```{r MBON, LHCENT, DNs, ANs and other matched types flywire}

gs4_auth("ts587@cam.ac.uk")
MBON = read_sheet("1bDaCiwdzg5BffT1b7CydUjrRlYtVL1Hwtsl-rQm7wUE")
MBONpts= subset(MBON$xyz,(!is.na(MBON$xyz)))
MBONid = flywire_xyz2id(MBONpts, rawcoords=TRUE)
MBONtype = subset(MBON$Type,(MBON$xyz!= 'NA'))
MBONname= data.frame(MBONtype, MBONid, MBONpts)
names(MBONname)[1] = "type"
names(MBONname)[2] = "post_id"
names(MBONname)[3] = "xyz"


LHCENT = read_sheet("1prxk5N4gekXEtGy2UdYKLCeF2XNU2I9IZr-2OJQTVjQ", sheet = 'master')
pts_R= subset(LHCENT$`Flywire R XYZ`,(!is.na(LHCENT$`Flywire R XYZ`)))
pts_L= subset(LHCENT$`Flywire L XYZ`,(!is.na(LHCENT$`Flywire L XYZ`)))
LHCENTpts = c(as.character(pts_R), as.character(pts_L))
LHCENTpts = LHCENTpts[LHCENTpts != "*"]
LHCENTid = flywire_xyz2id(LHCENTpts, rawcoords=TRUE)
LHCENTtype_R = subset(LHCENT$`FIB R name`,(!is.na(LHCENT$`Flywire R XYZ`)))
LHCENTtype_R = subset(LHCENT$`FIB R name`,(LHCENT$`Flywire R XYZ`!= "*"))
LHCENTtype_L = subset(LHCENT$`FIB R name`,(!is.na(LHCENT$`Flywire L XYZ`)))
LHCENTtype = c(as.character(LHCENTtype_R), as.character(LHCENTtype_L))
# LHCENTtype= unlist(LHCENTtype, use.names=FALSE)
LHCENTname= data.frame(LHCENTtype, LHCENTid, LHCENTpts)
names(LHCENTname)[1] = "type"
names(LHCENTname)[2] = "post_id"
names(LHCENTname)[3] = "xyz"

gs4_auth("tomke.stuerner@googlemail.com")
putative_DN = read_sheet("1vwlsODui1_kHCvLSyEWkbOoTwBZa52nJQNV_7BVSXc4", sheet = "FlyWire_DNs_April")
DNpts= subset(putative_DN$flywire.xyz,(!is.na(putative_DN$flywire.xyz)))
p_DNid = flywire_xyz2id(DNpts, rawcoords=TRUE)
DNpid = data.frame(DNpts,p_DNid)
DNtype = replicate(length(p_DNid), "DN")
DNname= data.frame(DNtype, p_DNid, DNpts)
names(DNname)[1] = "type"
names(DNname)[2] = "post_id"
names(DNname)[3] = "xyz"

AN = read_sheet("10T0JE6nVSz_uUdoHGOpV2odO_k75-arRPKdOiBXlS80", sheet = "ANs")
ANpts= subset(AN$flywire.xyz,(!is.na(AN$flywire.xyz)))
ANid = flywire_xyz2id(ANpts, rawcoords=TRUE)
ANtype = replicate(length(ANid), "AN")
ANname= data.frame(ANtype, ANid, ANpts)
names(ANname)[1] = "type"
names(ANname)[2] = "post_id"
names(ANname)[3] = "xyz"
# flywire_types= bind_rows(MBONname, LHCENTname, DNname, ANname)

matches = read_sheet("1OSlDtnR3B1LiB5cwI5x5Ql6LkZd8JOS5bBr-HTi0pOw", sheet = "hemibrain")
matchespts= subset(matches$flywire.xyz,(!is.na(matches$flywire.xyz)))
matchesid = flywire_xyz2id(matchespts, rawcoords=TRUE)
matchestype = subset(matches$cell.type,(matches$flywire.xyz!= 'NA'))
matchesname= data.frame(matchestype, matchesid, matchespts)
matchesname= matchesname[complete.cases(matchesname), ]
names(matchesname)[1] = "type"
names(matchesname)[2] = "post_id"
names(matchesname)[3] = "xyz"

gs4_auth("ts587@cam.ac.uk")
NoI = read_sheet("1HcaY5dXD_SoUuQ2Y7dE9q1pc6XX6nsfLDl26a9MxCOE", sheet = "multiglom_neurons")
NoIpts= subset(NoI$flywire.xyz,(!is.na(NoI$flywire.xyz)))
NoIid = flywire_xyz2id(NoIpts, rawcoords=TRUE)
NoItype = subset(NoI$name,(NoI$flywire.xyz!= 'NA'))
NoIname= data.frame(NoItype, NoIid, NoIpts)
NoIname= NoIname[complete.cases(NoIname), ]
names(NoIname)[1] = "type"
names(NoIname)[2] = "post_id"
names(NoIname)[3] = "xyz"


flywire_types= bind_rows(MBONname, LHCENTname, DNname, ANname, matchesname, NoIname)
# flywire_types= unique(flywire_types)
flywire_types= flywire_types%>% distinct(post_id, .keep_all = TRUE)
flywire_types
```

Neurotransmitter prediction:
```{r NT pred for all mPNs}
ntpred= flywire_ntpred(NoIname$post_id) #get neurotransmitter prediction for a neuron
names(NoIname)[2] = "query"
ntpred= left_join(NoIname, ntpred, by = "query")
ntpred
# # original URL (this will get auto-expanded as required)
# u="https://ngl.flywire.ai/?json_url=https://globalv1.flywire-daf.com/nglstate/6495872422510592"
# # update flywire_latestid
# ngl_segments(u) <- pbapply::pbsapply(ngl_segments(u), flywire_latestid)
# # updated long URL
# u
# # updated shortened URL
u="https://ngl.flywire.ai/?json_url=https://globalv1.flywire-daf.com/nglstate/6588467622445056"
sc=ngl_decode_scene(u)
# if you wanted to use the clipboard
# sc=ngl_decode_scene(clipr::read_clip())
segs=ngl_segments(sc)
# partners=flywire_partners(segs)
# # convert R list object back to URL
# browseURL(as.character(sc))
# # connection summary for those neurons
# pp=flywire_partner_summary(segs)
# gt200 <- pp %>%
#   group_by(post_id) %>%
#   arrange(query) %>%
#   summarise(n=n(), w=sum(weight), w1=weight[1], w2=weight[2]) %>%
#   arrange(desc(w)) %>%
#   filter(w>200)
# # add those (very strong) partners to the existing scene
# # and convert to URL
# u2=as.character(sc+gt200$post_id)
# neurotransmitter predictions for the starter neurons
segs = as.character(segs)
ntpreds <- sapply(segs, function(x) flywire_ntpred(x), simplify = FALSE)
  # sapply(segs, function(x) flywire_ntpred(x), simplify = FALSE)
ntpreds[[1]]
# flywire_ntpred("720575940634406030")
flywire_ntplot3d(ntpreds[[1]], plot = 'points', size=5, cleft.threshold = 100)

```

# Interconnectivity
1. M_spPN4t9 + M_l2PNl20 (+mALB1)
2. AL-MBDL1 + M_spPN5t10
3. ALBN1, M_vPNml50 with themselves
```{r connectivity of all neurons of interest to eachother}
"https://ngl.flywire.ai/?json_url=https://globalv1.flywire-daf.com/nglstate/5668177463738368"
NoI_conn=flywire_adjacency_matrix(NoIname$post_id)
colnames(NoI_conn) <- NoIname$type[match(colnames(NoI_conn), NoIname$post_id)]
rownames(NoI_conn) <- NoIname$type[match(rownames(NoI_conn), NoIname$post_id)]
# scaled to give proportion of inputs onto each target cell
# heatmap(NoI_conn, scale='col', cexRow = 0.5, cexCol = 0.5)
# scale='none' => raw counts
png(file= "NoI_interconnectivity.png",    # create PNG for the heat map        
  width = 5*300,        # 5 x 300 pixels
  height = 5*300,
  res = 300,            # 300 pixels per inch
  pointsize = 8)        # smaller font size

h=heatmap(NoI_conn, scale='none', keep.dendro = TRUE, cexRow = 0.5, cexCol = 0.5)
dev.off() # people often forget this step - did you?
# same but with the cleft threshold applied
# smc=flywire_adjacency_matrix(u, cleft.threshold = 30)
# h=heatmap(smc, scale='none', keep.dendro = TRUE)
```

```{r Common downstream partners}
# not avaiable for flywire, therefore check in neuprint
# 1. M_spPN4t9 + M_l2PNl20 (+mALB1) 5 common downstream targets (>10)
# 2. AL-MBDL1 + M_spPN5t10 NONE
test1= c("1316245799", "1671638278")
# test2= c("608922563", "731690040","1733370882")

# NoI$hemibrain.match= as.character(NoI$hemibrain.match)
# NOIhemibrainid= NoI$hemibrain.match
# NOIhemibrainid = subset(NOIhemibrainid,(!is.na(NOIhemibrainid)))

common = neuprint_common_connectivity(test1, prepost = "POST") # could use 'post' for downstream
# common = neuprint_common_connectivity(test2, prepost = "POST")
dim(common) 
common
rownames(common) = c("M_spPN4t9", "M_l2PNl20")

M_spPN4t9_M_l2PNl20 = as.data.frame(t(common))
M_spPN4t9_M_l2PNl20 = subset(M_spPN4t9_M_l2PNl20, M_spPN4t9_M_l2PNl20$M_spPN4t9 > 10)
M_spPN4t9_M_l2PNl20 = subset(M_spPN4t9_M_l2PNl20, M_spPN4t9_M_l2PNl20$M_l2PNl20 > 10)
c1 = rownames(M_spPN4t9_M_l2PNl20)
neuprint_get_meta(c1)
#  LHPV10b1_R, WEDPN6A_R, WEDPN4_R, M_lv2PN9t49_R, SMP081_R
```

Single neuron_type plots, transmitter and connectivity
Flywire neurons plot
```{r plot flywire neurons}

neuron_R =	"720575940628000567"
neuron_L =	"720575940616624182"
# neuron_R1 =	"720575940643268206"
# neuron_L1 =	"720575940631539993"

# neurons = c(neuron_R, neuron_L, neuron_R1, neuron_L1)
neurons = c(neuron_R, neuron_L)


neuronvol_R =	read_cloudvolume_meshes(neuron_R)
neuronvol_L =	read_cloudvolume_meshes(neuron_L)
# neuronvol_R1 =	read_cloudvolume_meshes(neuron_R1)
# neuronvol_L1 =	read_cloudvolume_meshes(neuron_L1)

# n1_CM = fetchn_fafb(11546775,mirror = FALSE,reference = "FlyWire")
open3d(userMatrix = structure(c(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1), .Dim = c(4L, 4L)), zoom = 0.644609212875366, 
       windowRect = c(0L, 45L, 1025L, 770L))
# plot3d(n1_CM, col = "magenta")
plot3d(neuronvol_R,add= TRUE, col = "green", alpha = 0.6)
plot3d(neuronvol_L,add= TRUE, col = "blue", alpha = 0.6)
# plot3d(neuronvol_R1,add= TRUE, col = "lightgreen", alpha = 0.6)
# plot3d(neuronvol_L1,add= TRUE, col = "lightblue", alpha = 0.6)
# dir.create("images")
# rgl.snapshot(filename = "./images/M_ilPN8t91_M_ilPNm90_Flywire.png" , fmt = "png" )
# rgl.snapshot(filename = "./images/M_spPN4t9_Flywire.png" , fmt = "png" )
# rgl.snapshot(filename = "./images/M_l2PNl20_Flywire.png" , fmt = "png" )
rgl.snapshot(filename = "./images/M_imPNl92_Flywire.png" , fmt = "png" ) #only one
# rgl.snapshot(filename = "./images/M_spPN5t10_Flywire.png" , fmt = "png" )
# rgl.snapshot(filename = "./images/M_vPNml50_Flywire.png" , fmt = "png" )
```

Upstream
```{r sum upstream partners}
# Partners_in = flywire_partners(neurons, partners = c("inputs"), details = TRUE) #get the upstream partners with synapse location
Partner_summary_in = flywire_partner_summary(neurons, partners = "inputs") #get a list of upstream partner with n synapse connected
names(flywire_types)[2] = "pre_id"
Partner_summary_in_types= left_join(Partner_summary_in, flywire_types, by = "pre_id")
Partner_summary_in_types_5 = subset(Partner_summary_in_types, Partner_summary_in_types$weight > 5)
Partner_summary_in_types_5 = Partner_summary_in_types_5[order(-Partner_summary_in_types_5$weight),]
# dir.create("connectivity")
# write.csv(Partner_summary_in_types_5, file = "./connectivity/M_l2PNl20_partner_summary_in_5.csv")
# write.csv(Partner_summary_in_types_5, file = "./connectivity/M_spPN4t9_partner_summary_in_5.csv")
# write.csv(Partner_summary_in_types_5, file = "./connectivity/M_ilPN8t91_M_ilPNm90_partner_summary_in_5.csv")
# write.csv(Partner_summary_in_types_5, file = "./connectivity/M_imPNl92_partner_summary_in_5.csv")
# write.csv(Partner_summary_in_types_5, file = "./connectivity/M_lvPNm24_partner_summary_in_5.csv")
# write.csv(Partner_summary_in_types_5, file = "./connectivity/M_spPN5t10_partner_summary_in_5.csv")
write.csv(Partner_summary_in_types_5, file = "./connectivity/M_vPNml50_partner_summary_in_5.csv")
Partner_summary_in_types_5
```
Downstream
```{r sum downstream partners}
# Partners_out = flywire_partners(neurons, partners = c("outputs"), details = TRUE) #get the upstream partners with synapse location
Partner_summary_out = flywire_partner_summary(neurons, partners = "outputs") #get a list of upstream partner with n synapse connected
names(flywire_types)[2] = "post_id"
Partner_summary_out_types= left_join(Partner_summary_out, flywire_types, by = "post_id")
Partner_summary_out_types_5 = subset(Partner_summary_out_types, Partner_summary_out_types$weight > 5)
Partner_summary_out_types_5 = Partner_summary_out_types_5[order(-Partner_summary_out_types_5$weight),]
# write.csv(Partner_summary_out_types_5, file = "./connectivity/M_spPN4t9_partner_summary_out_5.csv")
# write.csv(Partner_summary_out_types_5, file = "./connectivity/M_l2PNl20_partner_summary_out_5.csv")
# write.csv(Partner_summary_out_types_5, file = "./connectivity/M_ilPN8t91_M_ilPNm90_partner_summary_out_5.csv")
# write.csv(Partner_summary_out_types_5, file = "./connectivity/M_imPNl92_partner_summary_out_5.csv")
# write.csv(Partner_summary_out_types_5, file = "./connectivity/M_lvPNm24_partner_summary_out_5.csv")
# write.csv(Partner_summary_out_types_5, file = "./connectivity/M_spPN5t10_partner_summary_out_5.csv")
write.csv(Partner_summary_out_types_5, file = "./connectivity/M_vPNml50_partner_summary_out_5.csv")
Partner_summary_out_types_5
```
```{r plot downstream partners}
Partner_summary_out_types_50 = subset(Partner_summary_out_types_5, Partner_summary_out_types_5$weight > 50)
Partner_summary_out_types_50$query = as.character(Partner_summary_out_types_50$query)
Partner_summary_out_types_50$post_id = as.character(Partner_summary_out_types_50$post_id)
Partner_summary_out_types_50
Partner_out_plot = ggplot(Partner_summary_out_types_50, aes(x = query, y = type, fill = weight, )) +   geom_tile() + theme(text = element_text(size=8),axis.text.x = element_text(angle=90, hjust=1), axis.text.y = element_text(hjust=1))
# ggsave("./connectivity/M_l2PNl20_Partner_summary_out_types_50.png")
# ggsave("./connectivity/M_spPN4t9_Partner_summary_out_types_50.png")
# ggsave("./connectivity/M_ilPN8t91_M_ilPNm90_Partner_summary_out_types_50.png")
# ggsave("./connectivity/M_imPNl92_Partner_summary_out_types_50.png")
# ggsave("./connectivity/M_lvPNm24_Partner_summary_out_types_50.png")
# ggsave("./connectivity/M_spPN5t10_Partner_summary_out_types_50.png")
ggsave("./connectivity/M_vPNml50_Partner_summary_out_types_50.png")
Partner_out_plot
```