---
title: "mPNs"
author: "Tomke Stuerner"
date: "05/07/2021"
output: html_document
---
```{r, message=FALSE}
# neuprintr tutorial
# install
# natmanager::install('natverse')
if(!require('devtools')) install.packages("devtools")
if(!require('natverse')) devtools::install_github("natverse/natverse")
if (!requireNamespace("BiocManager", quietly = TRUE))install.packages("BiocManager")
if(!require('ComplexHeatmap')) BiocManager::install("ComplexHeatmap")
if(!require('ggnetwork')) install.packages("ggnetwork")
if(!require('network')) install.packages("network")
if(!require('neuprintr')) install.packages("neuprintr")
if(!require('googlesheets4')) install.packages("googlesheets4")
```

```{r}
# load
library(natverse)
library(hemibrainr)
library(neuprintr)
library(dendroextras)
library(ComplexHeatmap)
library(ggnetwork)
library(network)
library(googlesheets4)
library(dplyr)
library(catmaid)
library(fafbseg)
library(reticulate)
```

```{r}
# Colours
## some nice colors!! Inspired by LaCroixColoR
lacroix = c("#C70E7B", "#FC6882", "#007BC3", "#54BCD1", "#EF7C12", "#F4B95A", 
            "#009F3F", "#8FDA04", "#AF6125", "#F4E3C7", "#B25D91", "#EFC7E6", 
            "#EF7C12", "#F4B95A", "#C23A4B", "#FBBB48", "#EFEF46", "#31D64D", 
            "#132157","#EE4244", "#D72000", "#1BB6AF")
names(lacroix) = c("purple", "pink",
                   "blue", "cyan",
                   "darkorange", "paleorange",
                   "darkgreen", "green",
                   "brown", "palebrown",
                   "mauve", "lightpink",
                   "orange", "midorange",
                   "darkred", "darkyellow",
                   "yellow", "palegreen", 
                   "navy","cerise",
                   "red", "marine")
```

```{r}
## Then see if a simple function works for you:
available.datasets = neuprint_datasets()
available.datasets
```
```{r}
### all multiglomerular PNs in the Hemibrain dataset
mpn.info = neuprint_search("M_.*")
# mzpn.info = neuprint_search("MZ_.*")
# vPN.info = neuprint_search("VP.*+.*")
# 164 neurons
```
```{r load neurons}
mpn = neuprint_read_neurons(mpn.info$bodyid)
```
```{r plot hemibrain neurons}

open3d(userMatrix = structure(c(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1), .Dim = c(4L, 4L)), zoom = 0.644609212875366, 
       windowRect = c(0L, 45L, 1025L, 770L))
# AL=shapelist3d(lapply(c("AL(R)"), neuprint_ROI_mesh), plot = F)
wire3d(AL,col = 'grey', alpha = 0.05)
test = nlscan(mpn, col = 'red', lwd = 2)
test  
# "1702306047" "1671608112" "1701299822" "1671638278"
# "1700307582" "1102334088" "1888178718" "1671952694"
# "577542489"  "1316245799" "731690040"  "1733370882"
# "610274029"  "610274046" 
```
```{r mpn FAFB matches}
# # csv with PN clusters as in SchlegelBates et al S6: Comparison of ALPNs across three hemispheres.
# PN_cluster = read.csv("/Users/tomke/Documents/dev/temp/across_ds_clusters.csv")
# mPN_cluster = subset(PN_cluster, PN_cluster$ntype == "mPN")
# matches fro matching gsheet
matches = read_sheet("1OSlDtnR3B1LiB5cwI5x5Ql6LkZd8JOS5bBr-HTi0pOw", sheet = "hemibrain")
matchesFAFB = subset(matches,(!is.na(matches$FAFB.match)))
mPN_matches = matchesFAFB[grepl("^M_", matchesFAFB$cell.type), ]
```

```{r flywire}
choose_segmentation("flywire31")
catmaid_login() #this only works if you have your credentials saved in your environment
```

```{r plot flywire neurons}
mpn_fw_id = subset(mPN_matches$flywire.id, (!is.na(mPN_matches$flywire.id)))
# 161
mpn_fw = read_cloudvolume_meshes(mpn_fw_id)
```

```{r plot flywire neurons}
open3d(userMatrix = structure(c(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1), .Dim = c(4L, 4L)), zoom = 0.644609212875366, 
       windowRect = c(0L, 45L, 1025L, 770L))
test = nlscan(mpn_fw, col = 'red', lwd = 2)
test
# 720575940612616354, 720575940634406030,
# 720575940608771960, 720575940641817288,
# 720575940614141725, 720575940657653377,
# 720575940643268206, 720575940643267950,
# 720575940628308284, 720575940612992479,
# 720575940616841886, 720575940615096891,
# 720575940628217564, 720575940632553879,
# 720575940615488916, 720575940616942494,
# 720575940628000567, 720575940621817085,
# 720575940629475385, 720575940625508239
mPNs_test = subset(mPN_matches, mPN_matches$flywire.id == test)
```

2: M_ilPN8t91, M_ilPNm90_R
```{r interesting mPNs}

# x = mPN_matches[which(mPN_matches$flywire.id == "720575940615488916"), ]
x = mPN_matches[which(mPN_matches$flywire.id == "720575940616942494"), ]
x
```
M_imPNl92
```{r interesting mPNs}

x = mPN_matches[which(mPN_matches$bodyid == "1701299822"), ]
x
```
M_l2PNl20
```{r interesting mPNs}

x = mPN_matches[which(mPN_matches$flywire.id == "720575940612616354"), ]
x
```
M_l2PNl21?
```{r interesting mPNs}

x = mPN_matches[which(mPN_matches$bodyid == "1700307582"), ]
x
```
M_lvPNm24_R
```{r interesting mPNs}

x = mPN_matches[which(mPN_matches$bodyid == "1671952694"), ]
x = mPN_matches[which(mPN_matches$bodyid == "577542489"), ]
x
```


2: M_spPN5t10
```{r interesting mPNs}
# left
# x = mPN_matches[which(mPN_matches$bodyid == "731690040"), ]
x = mPN_matches[which(mPN_matches$flywire.id == "720575940625508239"), ]
x
```


M_spPN4t9
```{r interesting mPNs}

x = mPN_matches[which(mPN_matches$flywire.id == "720575940615096891"), ]
x
```
2: M_lv2PN9t49_R
```{r interesting mPNs}
# x = mPN_matches[which(mPN_matches$bodyid == "1888178718"), ]
x = mPN_matches[which(mPN_matches$bodyid == "1102334088"), ]
x
```

M_vPNml50_R